/** @format */

import type { Metadata } from 'next';
import { geistSans, geistMono } from '@/app/ui/fonts';
import '@/app/ui/globals.css';
import { UserProvider } from './context/UserContext';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>): React.ReactNode {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<UserProvider>{children}</UserProvider>
			</body>
		</html>
	);
}
